function buildTeacherApplicationMessage(application) {

return `🎓 Gopes Pinnacle Academy

Dear ${application.teacherName},

Your Faculty Application has been received successfully.

🆔 Application ID:
${application.applicationId}

📧 Please check your email for the complete application summary.

Our recruitment team will review your application and contact you regarding the next stage of the recruitment process.

Thank you for your interest in Gopes Pinnacle Academy.

🌐 www.gopespinnacle.com`;

}



function buildFounderApplicationMessage(application) {

return `🎓 Gopes Pinnacle Academy

📢 New Faculty Application Received

🆔 Application ID:
${application.applicationId}

👤 Name:
${application.teacherName}

📧 Email:
${application.email}

📱 Mobile:
${application.mobile}

🎓 Qualification:
${application.qualification}

Please review the complete application in the Founder ERP dashboard.

🌐 www.gopespinnacle.com`;

}

/* =========================================================
   STUDENT LOGIN CREDENTIALS WHATSAPP TEMPLATE
========================================================= */

function buildStudentLoginMessage(student) {

    return `🎓 *GOPES PINNACLE ACADEMY*

Dear Parent,

Greetings from Gopes Pinnacle Academy! 🌟

We are pleased to provide the login credentials for your ward's Academy Portal.

👤 *Student Name:* ${student.name || "Not Available"}

🆔 *Student ID:* ${student.studentId || "Not Available"}

🔐 *User ID:* ${student.loginEmail || student.email || "Not Available"}

🔑 *Password:* ${student.loginPassword || "Not Available"}

Please keep these login details safe and use them to access the Gopes Pinnacle Academy Student Portal.

We look forward to supporting your child's learning journey with us. 📚✨

Thank you,

*GOPES PINNACLE ACADEMY*

────────────────────

⚠️ *Please do not reply to this number.*
This is an autogenerated message.

For any communication, please contact:
📞 *+91-9566911472*`;
}



module.exports = {
    buildTeacherApplicationMessage,
    buildFounderApplicationMessage,
    buildStudentLoginMessage
};