function buildFacultyApplicationEmail(application) {

    return `

<!DOCTYPE html>

<html>

<head>

<meta charset="UTF-8">

<style>

body{

font-family:Arial,sans-serif;

background:#f4f6fb;

padding:30px;

}

.container{

max-width:850px;

margin:auto;

background:white;

padding:30px;

border-radius:10px;

border:1px solid #ddd;

}

.header{

text-align:center;

padding-bottom:20px;

border-bottom:2px solid #0d1b2a;

}

.header h1{

color:#0d1b2a;

margin:10px 0;

}

.section{

margin-top:25px;

}

table{

width:100%;

border-collapse:collapse;

}

td{

padding:8px;

border-bottom:1px solid #eee;

}

.title{

background:#0d1b2a;

color:white;

padding:10px;

font-weight:bold;

margin-top:25px;

}

.footer{

margin-top:40px;

font-size:13px;

color:#666;

text-align:center;

}

</style>

</head>

<body>

<div class="container">

<div class="header">

<h1>Gopes Pinnacle Academy</h1>

<h2>Faculty Application Received</h2>

</div>

<div class="title">

Application Information

</div>

<table>

<tr>

<td><b>Application ID</b></td>

<td>${application.applicationId}</td>

</tr>

<tr>

<td><b>Status</b></td>

<td>${application.applicationStatus}</td>

</tr>

<tr>

<td><b>Agreement Version</b></td>

<td>${application.agreementVersion}</td>

</tr>

</table>

<div class="title">

Applicant Information

</div>

<table>

<tr>

<td><b>Name</b></td>

<td>${application.teacherName}</td>

</tr>

<tr>

<td><b>Email</b></td>

<td>${application.email}</td>

</tr>

<tr>

<td><b>Mobile</b></td>

<td>${application.mobile}</td>

</tr>

<tr>

<td><b>Qualification</b></td>

<td>${application.education}</td>

</tr>

<tr>

<td><b>Experience</b></td>

<td>${application.experience}</td>

</tr>

</table>

<div class="title">

Application Acknowledgement

</div>

<p>

This email acknowledges that the applicant submitted a Faculty Application through the official Gopes Pinnacle Academy Recruitment Portal.

The application has been successfully received and recorded in the academy recruitment system.

</p>

<div class="title">

Freelance Educator Agreement Acceptance

</div>

<p>

During the online application process, the applicant confirmed acceptance of the Freelance Educator Terms & Conditions before submitting the application.

</p>

<table>

<tr>

<td><b>Agreement Status</b></td>

<td>Accepted</td>

</tr>

<tr>

<td><b>Agreement Version</b></td>

<td>${application.agreementVersion}</td>

</tr>

<tr>

<td><b>Accepted On</b></td>

<td>${application.agreementAcceptedOn}</td>

</tr>

</table>

<div class="title">

Teacher Declaration

</div>

<p>

${application.agreementAcceptedStatement}

</p>

<div class="title">

Freelance Educator Terms & Conditions

</div>

<div>

${application.agreementContent}

</div>

<div class="footer">

This email was automatically generated by the Gopes Pinnacle Academy ERP immediately after the application was submitted through the official recruitment portal.

Please retain this email for your records.

</div>

</div>

</body>

</html>

`;

}

module.exports = buildFacultyApplicationEmail;