const mongoose = require("mongoose");

const aiClassQuestionSchema = new mongoose.Schema({

    // Exact timetable period
    periodId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "TeacherSchedule",
        required: true
    },

    // Class information
    className: {
        type: String,
        default: ""
    },

    subject: {
        type: String,
        default: ""
    },

    teacherId: {
        type: String,
        default: ""
    },

    teacherName: {
        type: String,
        default: ""
    },

    // Live class session
    sessionId: {
        type: String,
        default: ""
    },

    // Question generated by AI
    question: {
        type: String,
        required: true
    },

    // Optional answer
    answer: {
        type: String,
        default: ""
    },

    // Question type
    questionType: {
        type: String,
        default: "application"
    },

    // Language used by AI
    language: {
        type: String,
        default: "English"
    },

    // When question was generated
    generatedAt: {
        type: Date,
        default: Date.now
    },

    // Which generation cycle
    generationNumber: {
        type: Number,
        default: 1
    },

    // Student answers
    responses: [

        {
            studentId: String,

            studentName: String,

            answer: String,

            isCorrect: Boolean,

            answeredAt: {
                type: Date,
                default: Date.now
            }
        }

    ]

}, {

    timestamps: true

});


module.exports = mongoose.model(
    "AIClassQuestion",
    aiClassQuestionSchema
);